### ISSUE TITLE
[Feat] Todo List 읽기 구현

### ISSUE THREAD

**Issue by vangona** [vangona/wanted-pre-onboarding-challenge-fe-1#3]
- [x] 간단한 레이아웃 구현 (목록 / 상세 영역 나누기)
- [x] Todo list와 item 컴포넌트 설계
- [x] Todo list와 item 컴포넌트 구현
- [x] Todo item 클릭 시 history push를 통해서 뒤로가기 버튼으로 조회 순서대로 조회할 수 있도록 구현
- [x] getTodos api 연결
- [x] url에 query를 추가해서 열려있는 todo detail 유지시키기
